### ISSUE TITLE
How you can make this repo "Up 6039" and top repository ?

### ISSUE THREAD

**Issue by iroy2000** [phase/sure#1]
I saw your repo showing up in top new repo as well as top starred repo, with 2 stars and "Up 6039", how can you do that ?? Seems interesting :)

**Comment by phase** [comment]
I was testing out to see how fast I get get 5,000 stars after I saw [this blogpost](http://thehackerblog.com/how-i-got-5000-github-followers-in-less-than-24-hours/#comment-72071). Mine was able to get me 1,000 every 10 minutes, but I didn't do any proxies so they shut me down pretty quickly. It's just abusing the fact that GitHub doesn't make you verify your email before you can star stuff.
